# Generated by Django 4.2.1 on 2023-05-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('fecha_vinculacion', models.DateField(verbose_name='Fecha vinculación')),
                ('modelo', models.IntegerField(default=0)),
                ('tipologia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concesionario_nombre', models.CharField(max_length=50)),
                ('concesionario_codigo', models.IntegerField(default=0)),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresast.vehiculo')),
            ],
        ),
    ]
