# Generated by Django 4.2.1 on 2023-05-16 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operador',
            name='placa',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresast.operador'),
        ),
    ]
