# Generated by Django 4.2.1 on 2023-05-17 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresast', '0002_remove_operador_placa_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='placa',
        ),
        migrations.DeleteModel(
            name='Operador',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
