# Generated by Django 4.2.2 on 2023-06-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresast', '0005_alter_vehiculo_concesionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='concesionario_nombre',
            field=models.CharField(max_length=50, verbose_name='Concesionario'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
