# Generated by Django 4.2.2 on 2023-06-08 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresast', '0006_alter_operador_concesionario_nombre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operador',
        ),
    ]
