# Generated by Django 4.2.2 on 2023-06-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresast', '0007_delete_operador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concesionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('concesionario_siglas', models.CharField(max_length=25, verbose_name='Siglas_Concesionario')),
                ('concesionario_nombre', models.CharField(max_length=100, verbose_name='Concesionario')),
            ],
        ),
    ]
