# Generated by Django 4.2.2 on 2023-06-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresast', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehiculo_estado', models.CharField(max_length=100, verbose_name='estado')),
                ('vehiculo_etiqueta', models.CharField(max_length=10, verbose_name='etiqueta')),
                ('vehiculo_placa', models.CharField(max_length=7, verbose_name='placa')),
                ('vehiculo_concesionario', models.CharField(max_length=8, verbose_name='concesionario')),
            ],
        ),
    ]
